# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd67093249ef6b216c1a27b823f45eac870d1d7dc874bd5007615ea8cef2803701fc102bf73b690b61dc70e42c87ad0cd820036e391e751d0f9d1ff74794c927

test:
  secret_key_base: 94244216b99f9931b816b90ac2fcf23a94fb82028345ecdf4a71c2b03f4a010c8e7c1c8edbea6a0bcedebdcf7c5516a8a2455b8a34de20a4fa83fdd3e6def37d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
